---
title: "Lab 7 Assignment: Group 11"
format:
  html:
    embed-resources: true
editor: visual
---

## GROUP 11:

#### Eleni-Sofia Tseperi s240066, Johanne Lund s233246, Marie Picquet s233736, Eglantine Anton s233242, Wu Qiuyan s241063

## Background

## Aim

## Load Library

```{r}
#| echo: True
#| eval: false
library(tidyverse, verbose = FALSE)
library(ggplot2, verbose = FALSE)
library(broom)

```

## Load Data

```{r}
#| echo: True
#| eval: false
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

## Data Description

## Analysis

Normalization and getting the PCR:

```{r}
pca_data <- biopsy |> 
  select(where(is.numeric)) |> 
  scale() |> 
  prcomp() 
```

Plotting the

```{r}
pca_data |>
  augment(biopsy) |> # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "purple", benign = "lightgreen")
  ) +
  theme_half_open(12) + background_grid() +
  labs(title="PC coordinates in scatterplot",
       subtitle = "Breast cancer biopsy dataset", x="Fitted PC1", y = "Fitted PC2", color="Outcome", caption="Source: https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv") +
  theme(legend.position = "bottom")
```

```{r}
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)


pca_fit |>
  tidy(matrix = "rotation") |>
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") |>
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "purple"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed() + 
  theme_minimal_grid(12) +
  labs(title="Rotation matrix",
       subtitle = "Breast cancer biopsy dataset", x="PC1", y = "PC2", caption="Source: https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

plot:

```{r}
pca_data |>
  augment(biopsy) |> # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#D55E00", benign = "#0072B2")
  ) +
  theme_half_open(12) + background_grid()
```
